export const SHOW_PROJECT_ADD_DIALOG = 'SHOW_PROJECT_ADD_DIALOG';
export const HIDE_PROJECT_ADD_DIALOG = 'HIDE_PROJECT_ADD_DIALOG';

export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE';