export const SHOW_MAIN_LOADER = 'SHOW_MAIN_LOADER';
export const HIDE_MAIN_LOADER = 'HIDE_MAIN_LOADER';

export const SHOW_MAIN_SNACKBAR = 'SHOW_MAIN_SNACKBAR';
export const HIDE_MAIN_SNACKBAR = 'HIDE_MAIN_SNACKBAR';