export const SHOW_MAIN_DRAWER = 'SHOW_MAIN_DRAWER';
export const HIDE_MAIN_DRAWER = 'HIDE_MAIN_DRAWER';

export const SHOW_MAIN_LOADER = 'SHOW_MAIN_LOADER';
export const HIDE_MAIN_LOADER = 'HIDE_MAIN_LOADER';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const PUSH_SNACKBAR_MESSAGE = 'PUSH_SNACKBAR_MESSAGE';

export const SWITCH_PROJECTS_LAYOUT = 'SWITCH_PROJECTS_LAYOUT';